/*
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha1;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ArchiveStrategy describes how to archive files/directory when saving artifacts
 */
@ApiModel(description = "ArchiveStrategy describes how to archive files/directory when saving artifacts")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-02T13:36:12.841+03:30[Asia/Tehran]")
public class ArchiveStrategy {
  public static final String SERIALIZED_NAME_NONE = "none";
  @SerializedName(SERIALIZED_NAME_NONE)
  private Object none = null;

  public static final String SERIALIZED_NAME_TAR = "tar";
  @SerializedName(SERIALIZED_NAME_TAR)
  private Object tar = null;

  public ArchiveStrategy none(Object none) {
    this.none = none;
    return this;
  }

   /**
   * NoneStrategy indicates to skip tar process and upload the files or directory tree as independent files. Note that if the artifact is a directory, the artifact driver must support the ability to save/load the directory appropriately.
   * @return none
  **/
  @ApiModelProperty(value = "NoneStrategy indicates to skip tar process and upload the files or directory tree as independent files. Note that if the artifact is a directory, the artifact driver must support the ability to save/load the directory appropriately.")
  public Object getNone() {
    return none;
  }

  public void setNone(Object none) {
    this.none = none;
  }

  public ArchiveStrategy tar(Object tar) {
    this.tar = tar;
    return this;
  }

   /**
   * TarStrategy will tar and gzip the file or directory when saving
   * @return tar
  **/
  @ApiModelProperty(value = "TarStrategy will tar and gzip the file or directory when saving")
  public Object getTar() {
    return tar;
  }

  public void setTar(Object tar) {
    this.tar = tar;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArchiveStrategy ioArgoprojWorkflowV1alpha1ArchiveStrategy = (ArchiveStrategy) o;
    return Objects.equals(this.none, ioArgoprojWorkflowV1alpha1ArchiveStrategy.none) &&
        Objects.equals(this.tar, ioArgoprojWorkflowV1alpha1ArchiveStrategy.tar);
  }

  @Override
  public int hashCode() {
    return Objects.hash(none, tar);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1ArchiveStrategy {\n");
    sb.append("    none: ").append(toIndentedString(none)).append("\n");
    sb.append("    tar: ").append(toIndentedString(tar)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

