/*
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha1;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha1.DAGTask;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DAGTemplate is a template subtype for directed acyclic graph templates
 */
@ApiModel(description = "DAGTemplate is a template subtype for directed acyclic graph templates")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-02T13:36:12.841+03:30[Asia/Tehran]")
public class DAGTemplate {
  public static final String SERIALIZED_NAME_TARGET = "target";
  @SerializedName(SERIALIZED_NAME_TARGET)
  private String target;

  public static final String SERIALIZED_NAME_TASKS = "tasks";
  @SerializedName(SERIALIZED_NAME_TASKS)
  private List<DAGTask> tasks = new ArrayList<DAGTask>();

  public DAGTemplate target(String target) {
    this.target = target;
    return this;
  }

   /**
   * Target are one or more names of targets to execute in a DAG
   * @return target
  **/
  @ApiModelProperty(value = "Target are one or more names of targets to execute in a DAG")
  public String getTarget() {
    return target;
  }

  public void setTarget(String target) {
    this.target = target;
  }

  public DAGTemplate tasks(List<DAGTask> tasks) {
    this.tasks = tasks;
    return this;
  }

  public DAGTemplate addTasksItem(DAGTask tasksItem) {
    this.tasks.add(tasksItem);
    return this;
  }

   /**
   * Tasks are a list of DAG tasks
   * @return tasks
  **/
  @ApiModelProperty(required = true, value = "Tasks are a list of DAG tasks")
  public List<DAGTask> getTasks() {
    return tasks;
  }

  public void setTasks(List<DAGTask> tasks) {
    this.tasks = tasks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DAGTemplate ioArgoprojWorkflowV1alpha1DAGTemplate = (DAGTemplate) o;
    return Objects.equals(this.target, ioArgoprojWorkflowV1alpha1DAGTemplate.target) &&
        Objects.equals(this.tasks, ioArgoprojWorkflowV1alpha1DAGTemplate.tasks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(target, tasks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1DAGTemplate {\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    tasks: ").append(toIndentedString(tasks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

