/*
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha1;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.proto.V1.SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GitArtifact is the location of an git artifact
 */
@ApiModel(description = "GitArtifact is the location of an git artifact")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-02T13:36:12.841+03:30[Asia/Tehran]")
public class GitArtifact {
  public static final String SERIALIZED_NAME_PASSWORD_SECRET = "passwordSecret";
  @SerializedName(SERIALIZED_NAME_PASSWORD_SECRET)
  private SecretKeySelector passwordSecret = null;

  public static final String SERIALIZED_NAME_REPO = "repo";
  @SerializedName(SERIALIZED_NAME_REPO)
  private String repo;

  public static final String SERIALIZED_NAME_REVISION = "revision";
  @SerializedName(SERIALIZED_NAME_REVISION)
  private String revision;

  public static final String SERIALIZED_NAME_SSH_PRIVATE_KEY_SECRET = "sshPrivateKeySecret";
  @SerializedName(SERIALIZED_NAME_SSH_PRIVATE_KEY_SECRET)
  private SecretKeySelector sshPrivateKeySecret = null;

  public static final String SERIALIZED_NAME_USERNAME_SECRET = "usernameSecret";
  @SerializedName(SERIALIZED_NAME_USERNAME_SECRET)
  private SecretKeySelector usernameSecret = null;

  public GitArtifact passwordSecret(SecretKeySelector passwordSecret) {
    this.passwordSecret = passwordSecret;
    return this;
  }

   /**
   * Get passwordSecret
   * @return passwordSecret
  **/
  @ApiModelProperty(value = "")
  public SecretKeySelector getPasswordSecret() {
    return passwordSecret;
  }

  public void setPasswordSecret(SecretKeySelector passwordSecret) {
    this.passwordSecret = passwordSecret;
  }

  public GitArtifact repo(String repo) {
    this.repo = repo;
    return this;
  }

   /**
   * Repo is the git repository
   * @return repo
  **/
  @ApiModelProperty(required = true, value = "Repo is the git repository")
  public String getRepo() {
    return repo;
  }

  public void setRepo(String repo) {
    this.repo = repo;
  }

  public GitArtifact revision(String revision) {
    this.revision = revision;
    return this;
  }

   /**
   * Revision is the git commit, tag, branch to checkout
   * @return revision
  **/
  @ApiModelProperty(value = "Revision is the git commit, tag, branch to checkout")
  public String getRevision() {
    return revision;
  }

  public void setRevision(String revision) {
    this.revision = revision;
  }

  public GitArtifact sshPrivateKeySecret(SecretKeySelector sshPrivateKeySecret) {
    this.sshPrivateKeySecret = sshPrivateKeySecret;
    return this;
  }

   /**
   * Get sshPrivateKeySecret
   * @return sshPrivateKeySecret
  **/
  @ApiModelProperty(value = "")
  public SecretKeySelector getSshPrivateKeySecret() {
    return sshPrivateKeySecret;
  }

  public void setSshPrivateKeySecret(SecretKeySelector sshPrivateKeySecret) {
    this.sshPrivateKeySecret = sshPrivateKeySecret;
  }

  public GitArtifact usernameSecret(SecretKeySelector usernameSecret) {
    this.usernameSecret = usernameSecret;
    return this;
  }

   /**
   * Get usernameSecret
   * @return usernameSecret
  **/
  @ApiModelProperty(value = "")
  public SecretKeySelector getUsernameSecret() {
    return usernameSecret;
  }

  public void setUsernameSecret(SecretKeySelector usernameSecret) {
    this.usernameSecret = usernameSecret;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GitArtifact ioArgoprojWorkflowV1alpha1GitArtifact = (GitArtifact) o;
    return Objects.equals(this.passwordSecret, ioArgoprojWorkflowV1alpha1GitArtifact.passwordSecret) &&
        Objects.equals(this.repo, ioArgoprojWorkflowV1alpha1GitArtifact.repo) &&
        Objects.equals(this.revision, ioArgoprojWorkflowV1alpha1GitArtifact.revision) &&
        Objects.equals(this.sshPrivateKeySecret, ioArgoprojWorkflowV1alpha1GitArtifact.sshPrivateKeySecret) &&
        Objects.equals(this.usernameSecret, ioArgoprojWorkflowV1alpha1GitArtifact.usernameSecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(passwordSecret, repo, revision, sshPrivateKeySecret, usernameSecret);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1GitArtifact {\n");
    sb.append("    passwordSecret: ").append(toIndentedString(passwordSecret)).append("\n");
    sb.append("    repo: ").append(toIndentedString(repo)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    sshPrivateKeySecret: ").append(toIndentedString(sshPrivateKeySecret)).append("\n");
    sb.append("    usernameSecret: ").append(toIndentedString(usernameSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

