/*
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha1;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResourceTemplate is a template subtype to manipulate kubernetes resources
 */
@ApiModel(description = "ResourceTemplate is a template subtype to manipulate kubernetes resources")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-02T13:36:12.841+03:30[Asia/Tehran]")
public class ResourceTemplate {
  public static final String SERIALIZED_NAME_ACTION = "action";
  @SerializedName(SERIALIZED_NAME_ACTION)
  private String action;

  public static final String SERIALIZED_NAME_FAILURE_CONDITION = "failureCondition";
  @SerializedName(SERIALIZED_NAME_FAILURE_CONDITION)
  private String failureCondition;

  public static final String SERIALIZED_NAME_MANIFEST = "manifest";
  @SerializedName(SERIALIZED_NAME_MANIFEST)
  private String manifest;

  public static final String SERIALIZED_NAME_SUCCESS_CONDITION = "successCondition";
  @SerializedName(SERIALIZED_NAME_SUCCESS_CONDITION)
  private String successCondition;

  public ResourceTemplate action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Action is the action to perform to the resource. Must be one of: get, create, apply, delete, replace
   * @return action
  **/
  @ApiModelProperty(required = true, value = "Action is the action to perform to the resource. Must be one of: get, create, apply, delete, replace")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public ResourceTemplate failureCondition(String failureCondition) {
    this.failureCondition = failureCondition;
    return this;
  }

   /**
   * FailureCondition is a label selector expression which describes the conditions of the k8s resource in which the step was considered failed
   * @return failureCondition
  **/
  @ApiModelProperty(value = "FailureCondition is a label selector expression which describes the conditions of the k8s resource in which the step was considered failed")
  public String getFailureCondition() {
    return failureCondition;
  }

  public void setFailureCondition(String failureCondition) {
    this.failureCondition = failureCondition;
  }

  public ResourceTemplate manifest(String manifest) {
    this.manifest = manifest;
    return this;
  }

   /**
   * Manifest contains the kubernetes manifest
   * @return manifest
  **/
  @ApiModelProperty(required = true, value = "Manifest contains the kubernetes manifest")
  public String getManifest() {
    return manifest;
  }

  public void setManifest(String manifest) {
    this.manifest = manifest;
  }

  public ResourceTemplate successCondition(String successCondition) {
    this.successCondition = successCondition;
    return this;
  }

   /**
   * SuccessCondition is a label selector expression which describes the conditions of the k8s resource in which it is acceptable to proceed to the following step
   * @return successCondition
  **/
  @ApiModelProperty(value = "SuccessCondition is a label selector expression which describes the conditions of the k8s resource in which it is acceptable to proceed to the following step")
  public String getSuccessCondition() {
    return successCondition;
  }

  public void setSuccessCondition(String successCondition) {
    this.successCondition = successCondition;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceTemplate ioArgoprojWorkflowV1alpha1ResourceTemplate = (ResourceTemplate) o;
    return Objects.equals(this.action, ioArgoprojWorkflowV1alpha1ResourceTemplate.action) &&
        Objects.equals(this.failureCondition, ioArgoprojWorkflowV1alpha1ResourceTemplate.failureCondition) &&
        Objects.equals(this.manifest, ioArgoprojWorkflowV1alpha1ResourceTemplate.manifest) &&
        Objects.equals(this.successCondition, ioArgoprojWorkflowV1alpha1ResourceTemplate.successCondition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, failureCondition, manifest, successCondition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1ResourceTemplate {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    failureCondition: ").append(toIndentedString(failureCondition)).append("\n");
    sb.append("    manifest: ").append(toIndentedString(manifest)).append("\n");
    sb.append("    successCondition: ").append(toIndentedString(successCondition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

