/*
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha1;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.kubernetes.client.proto.V1.SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * S3Artifact is the location of an S3 artifact
 */
@ApiModel(description = "S3Artifact is the location of an S3 artifact")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-02T13:36:12.841+03:30[Asia/Tehran]")
public class S3Artifact {
  public static final String SERIALIZED_NAME_ACCESS_KEY_SECRET = "accessKeySecret";
  @SerializedName(SERIALIZED_NAME_ACCESS_KEY_SECRET)
  private SecretKeySelector accessKeySecret = null;

  public static final String SERIALIZED_NAME_BUCKET = "bucket";
  @SerializedName(SERIALIZED_NAME_BUCKET)
  private String bucket;

  public static final String SERIALIZED_NAME_ENDPOINT = "endpoint";
  @SerializedName(SERIALIZED_NAME_ENDPOINT)
  private String endpoint;

  public static final String SERIALIZED_NAME_INSECURE = "insecure";
  @SerializedName(SERIALIZED_NAME_INSECURE)
  private Boolean insecure;

  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  private String region;

  public static final String SERIALIZED_NAME_SECRET_KEY_SECRET = "secretKeySecret";
  @SerializedName(SERIALIZED_NAME_SECRET_KEY_SECRET)
  private SecretKeySelector secretKeySecret = null;

  public S3Artifact accessKeySecret(SecretKeySelector accessKeySecret) {
    this.accessKeySecret = accessKeySecret;
    return this;
  }

   /**
   * Get accessKeySecret
   * @return accessKeySecret
  **/
  @ApiModelProperty(required = true, value = "")
  public SecretKeySelector getAccessKeySecret() {
    return accessKeySecret;
  }

  public void setAccessKeySecret(SecretKeySelector accessKeySecret) {
    this.accessKeySecret = accessKeySecret;
  }

  public S3Artifact bucket(String bucket) {
    this.bucket = bucket;
    return this;
  }

   /**
   * Bucket is the name of the bucket
   * @return bucket
  **/
  @ApiModelProperty(required = true, value = "Bucket is the name of the bucket")
  public String getBucket() {
    return bucket;
  }

  public void setBucket(String bucket) {
    this.bucket = bucket;
  }

  public S3Artifact endpoint(String endpoint) {
    this.endpoint = endpoint;
    return this;
  }

   /**
   * Endpoint is the hostname of the bucket endpoint
   * @return endpoint
  **/
  @ApiModelProperty(required = true, value = "Endpoint is the hostname of the bucket endpoint")
  public String getEndpoint() {
    return endpoint;
  }

  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }

  public S3Artifact insecure(Boolean insecure) {
    this.insecure = insecure;
    return this;
  }

   /**
   * Insecure will connect to the service with TLS
   * @return insecure
  **/
  @ApiModelProperty(value = "Insecure will connect to the service with TLS")
  public Boolean getInsecure() {
    return insecure;
  }

  public void setInsecure(Boolean insecure) {
    this.insecure = insecure;
  }

  public S3Artifact key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Key is the key in the bucket where the artifact resides
   * @return key
  **/
  @ApiModelProperty(required = true, value = "Key is the key in the bucket where the artifact resides")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public S3Artifact region(String region) {
    this.region = region;
    return this;
  }

   /**
   * Region contains the optional bucket region
   * @return region
  **/
  @ApiModelProperty(value = "Region contains the optional bucket region")
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public S3Artifact secretKeySecret(SecretKeySelector secretKeySecret) {
    this.secretKeySecret = secretKeySecret;
    return this;
  }

   /**
   * Get secretKeySecret
   * @return secretKeySecret
  **/
  @ApiModelProperty(required = true, value = "")
  public SecretKeySelector getSecretKeySecret() {
    return secretKeySecret;
  }

  public void setSecretKeySecret(SecretKeySelector secretKeySecret) {
    this.secretKeySecret = secretKeySecret;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    S3Artifact ioArgoprojWorkflowV1alpha1S3Artifact = (S3Artifact) o;
    return Objects.equals(this.accessKeySecret, ioArgoprojWorkflowV1alpha1S3Artifact.accessKeySecret) &&
        Objects.equals(this.bucket, ioArgoprojWorkflowV1alpha1S3Artifact.bucket) &&
        Objects.equals(this.endpoint, ioArgoprojWorkflowV1alpha1S3Artifact.endpoint) &&
        Objects.equals(this.insecure, ioArgoprojWorkflowV1alpha1S3Artifact.insecure) &&
        Objects.equals(this.key, ioArgoprojWorkflowV1alpha1S3Artifact.key) &&
        Objects.equals(this.region, ioArgoprojWorkflowV1alpha1S3Artifact.region) &&
        Objects.equals(this.secretKeySecret, ioArgoprojWorkflowV1alpha1S3Artifact.secretKeySecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessKeySecret, bucket, endpoint, insecure, key, region, secretKeySecret);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1S3Artifact {\n");
    sb.append("    accessKeySecret: ").append(toIndentedString(accessKeySecret)).append("\n");
    sb.append("    bucket: ").append(toIndentedString(bucket)).append("\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    insecure: ").append(toIndentedString(insecure)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    secretKeySecret: ").append(toIndentedString(secretKeySecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

