/*
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha.ArchiveStrategy;
import io.argoproj.workflow.v1alpha.ArtifactoryArtifact;
import io.argoproj.workflow.v1alpha.GitArtifact;
import io.argoproj.workflow.v1alpha.HDFSArtifact;
import io.argoproj.workflow.v1alpha.HTTPArtifact;
import io.argoproj.workflow.v1alpha.RawArtifact;
import io.argoproj.workflow.v1alpha.S3Artifact;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Artifact
 */
public class ArtifactTest {
    private final Artifact model = new Artifact();

    /**
     * Model tests for Artifact
     */
    @Test
    public void testArtifact() {
        // TODO: test Artifact
    }

    /**
     * Test the property 'archive'
     */
    @Test
    public void archiveTest() {
        // TODO: test archive
    }

    /**
     * Test the property 'archiveLogs'
     */
    @Test
    public void archiveLogsTest() {
        // TODO: test archiveLogs
    }

    /**
     * Test the property 'artifactory'
     */
    @Test
    public void artifactoryTest() {
        // TODO: test artifactory
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'git'
     */
    @Test
    public void gitTest() {
        // TODO: test git
    }

    /**
     * Test the property 'globalName'
     */
    @Test
    public void globalNameTest() {
        // TODO: test globalName
    }

    /**
     * Test the property 'hdfs'
     */
    @Test
    public void hdfsTest() {
        // TODO: test hdfs
    }

    /**
     * Test the property 'http'
     */
    @Test
    public void httpTest() {
        // TODO: test http
    }

    /**
     * Test the property 'mode'
     */
    @Test
    public void modeTest() {
        // TODO: test mode
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'optional'
     */
    @Test
    public void optionalTest() {
        // TODO: test optional
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'raw'
     */
    @Test
    public void rawTest() {
        // TODO: test raw
    }

    /**
     * Test the property 's3'
     */
    @Test
    public void s3Test() {
        // TODO: test s3
    }

}
