/*
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.models.V1ConfigMapKeySelector;
import io.kubernetes.client.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HDFSKrbConfig
 */
public class HDFSKrbConfigTest {
    private final HDFSKrbConfig model = new HDFSKrbConfig();

    /**
     * Model tests for HDFSKrbConfig
     */
    @Test
    public void testHDFSKrbConfig() {
        // TODO: test HDFSKrbConfig
    }

    /**
     * Test the property 'krbCCacheSecret'
     */
    @Test
    public void krbCCacheSecretTest() {
        // TODO: test krbCCacheSecret
    }

    /**
     * Test the property 'krbConfigConfigMap'
     */
    @Test
    public void krbConfigConfigMapTest() {
        // TODO: test krbConfigConfigMap
    }

    /**
     * Test the property 'krbKeytabSecret'
     */
    @Test
    public void krbKeytabSecretTest() {
        // TODO: test krbKeytabSecret
    }

    /**
     * Test the property 'krbRealm'
     */
    @Test
    public void krbRealmTest() {
        // TODO: test krbRealm
    }

    /**
     * Test the property 'krbServicePrincipalName'
     */
    @Test
    public void krbServicePrincipalNameTest() {
        // TODO: test krbServicePrincipalName
    }

    /**
     * Test the property 'krbUsername'
     */
    @Test
    public void krbUsernameTest() {
        // TODO: test krbUsername
    }

}
