/*
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ItemValue
 */
public class ItemValueTest {
    private final ItemValue model = new ItemValue();

    /**
     * Model tests for ItemValue
     */
    @Test
    public void testItemValue() {
        // TODO: test ItemValue
    }

    /**
     * Test the property 'boolVal'
     */
    @Test
    public void boolValTest() {
        // TODO: test boolVal
    }

    /**
     * Test the property 'listVal'
     */
    @Test
    public void listValTest() {
        // TODO: test listVal
    }

    /**
     * Test the property 'mapVal'
     */
    @Test
    public void mapValTest() {
        // TODO: test mapVal
    }

    /**
     * Test the property 'numVal'
     */
    @Test
    public void numValTest() {
        // TODO: test numVal
    }

    /**
     * Test the property 'strVal'
     */
    @Test
    public void strValTest() {
        // TODO: test strVal
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
