/*
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha.NodeStatus;
import io.argoproj.workflow.v1alpha.Outputs;
import io.argoproj.workflow.v1alpha.Template;
import io.kubernetes.client.models.V1Volume;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.joda.time.DateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WorkflowStatus
 */
public class WorkflowStatusTest {
    private final WorkflowStatus model = new WorkflowStatus();

    /**
     * Model tests for WorkflowStatus
     */
    @Test
    public void testWorkflowStatus() {
        // TODO: test WorkflowStatus
    }

    /**
     * Test the property 'compressedNodes'
     */
    @Test
    public void compressedNodesTest() {
        // TODO: test compressedNodes
    }

    /**
     * Test the property 'finishedAt'
     */
    @Test
    public void finishedAtTest() {
        // TODO: test finishedAt
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'nodes'
     */
    @Test
    public void nodesTest() {
        // TODO: test nodes
    }

    /**
     * Test the property 'offloadNodeStatusVersion'
     */
    @Test
    public void offloadNodeStatusVersionTest() {
        // TODO: test offloadNodeStatusVersion
    }

    /**
     * Test the property 'outputs'
     */
    @Test
    public void outputsTest() {
        // TODO: test outputs
    }

    /**
     * Test the property 'persistentVolumeClaims'
     */
    @Test
    public void persistentVolumeClaimsTest() {
        // TODO: test persistentVolumeClaims
    }

    /**
     * Test the property 'phase'
     */
    @Test
    public void phaseTest() {
        // TODO: test phase
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'storedTemplates'
     */
    @Test
    public void storedTemplatesTest() {
        // TODO: test storedTemplates
    }

}
