/*
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha1;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojWorkflowV1alpha1ArtifactoryAuth
 */
public class ArtifactoryAuthTest {
    private final ArtifactoryAuth model = new ArtifactoryAuth();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1ArtifactoryAuth
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1ArtifactoryAuth() {
        // TODO: test IoArgoprojWorkflowV1alpha1ArtifactoryAuth
    }

    /**
     * Test the property 'passwordSecret'
     */
    @Test
    public void passwordSecretTest() {
        // TODO: test passwordSecret
    }

    /**
     * Test the property 'usernameSecret'
     */
    @Test
    public void usernameSecretTest() {
        // TODO: test usernameSecret
    }

}
