/*
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha1;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha1.ArtifactoryArtifact;
import io.argoproj.workflow.v1alpha1.GitArtifact;
import io.argoproj.workflow.v1alpha1.HDFSArtifact;
import io.argoproj.workflow.v1alpha1.HTTPArtifact;
import io.argoproj.workflow.v1alpha1.RawArtifact;
import io.argoproj.workflow.v1alpha1.S3Artifact;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojWorkflowV1alpha1ArtifactLocation
 */
public class ArtifactLocationTest {
    private final ArtifactLocation model = new ArtifactLocation();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1ArtifactLocation
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1ArtifactLocation() {
        // TODO: test IoArgoprojWorkflowV1alpha1ArtifactLocation
    }

    /**
     * Test the property 'archiveLogs'
     */
    @Test
    public void archiveLogsTest() {
        // TODO: test archiveLogs
    }

    /**
     * Test the property 'artifactory'
     */
    @Test
    public void artifactoryTest() {
        // TODO: test artifactory
    }

    /**
     * Test the property 'git'
     */
    @Test
    public void gitTest() {
        // TODO: test git
    }

    /**
     * Test the property 'hdfs'
     */
    @Test
    public void hdfsTest() {
        // TODO: test hdfs
    }

    /**
     * Test the property 'http'
     */
    @Test
    public void httpTest() {
        // TODO: test http
    }

    /**
     * Test the property 'raw'
     */
    @Test
    public void rawTest() {
        // TODO: test raw
    }

    /**
     * Test the property 's3'
     */
    @Test
    public void s3Test() {
        // TODO: test s3
    }

}
