/*
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha1;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha1.Arguments;
import io.argoproj.workflow.v1alpha1.Sequence;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojWorkflowV1alpha1DAGTask
 */
public class IoArgoprojWorkflowV1alpha1DAGTaskTest {
    private final DAGTask model = new DAGTask();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1DAGTask
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1DAGTask() {
        // TODO: test IoArgoprojWorkflowV1alpha1DAGTask
    }

    /**
     * Test the property 'arguments'
     */
    @Test
    public void argumentsTest() {
        // TODO: test arguments
    }

    /**
     * Test the property 'dependencies'
     */
    @Test
    public void dependenciesTest() {
        // TODO: test dependencies
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'when'
     */
    @Test
    public void whenTest() {
        // TODO: test when
    }

    /**
     * Test the property 'withItems'
     */
    @Test
    public void withItemsTest() {
        // TODO: test withItems
    }

    /**
     * Test the property 'withParam'
     */
    @Test
    public void withParamTest() {
        // TODO: test withParam
    }

    /**
     * Test the property 'withSequence'
     */
    @Test
    public void withSequenceTest() {
        // TODO: test withSequence
    }

}
