/*
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha1;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha1.Arguments;
import io.argoproj.workflow.v1alpha1.Template;
import io.argoproj.workflow.v1alpha1.IoK8sApiCoreV1Affinity;
import io.argoproj.workflow.v1alpha1.IoK8sApiCoreV1LocalObjectReference;
import io.argoproj.workflow.v1alpha1.IoK8sApiCoreV1PersistentVolumeClaim;
import io.argoproj.workflow.v1alpha1.IoK8sApiCoreV1Toleration;
import io.argoproj.workflow.v1alpha1.IoK8sApiCoreV1Volume;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojWorkflowV1alpha1WorkflowSpec
 */
public class IoArgoprojWorkflowV1alpha1WorkflowSpecTest {
    private final WorkflowSpec model = new WorkflowSpec();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1WorkflowSpec() {
        // TODO: test IoArgoprojWorkflowV1alpha1WorkflowSpec
    }

    /**
     * Test the property 'activeDeadlineSeconds'
     */
    @Test
    public void activeDeadlineSecondsTest() {
        // TODO: test activeDeadlineSeconds
    }

    /**
     * Test the property 'affinity'
     */
    @Test
    public void affinityTest() {
        // TODO: test affinity
    }

    /**
     * Test the property 'arguments'
     */
    @Test
    public void argumentsTest() {
        // TODO: test arguments
    }

    /**
     * Test the property 'dnsPolicy'
     */
    @Test
    public void dnsPolicyTest() {
        // TODO: test dnsPolicy
    }

    /**
     * Test the property 'entrypoint'
     */
    @Test
    public void entrypointTest() {
        // TODO: test entrypoint
    }

    /**
     * Test the property 'hostNetwork'
     */
    @Test
    public void hostNetworkTest() {
        // TODO: test hostNetwork
    }

    /**
     * Test the property 'imagePullSecrets'
     */
    @Test
    public void imagePullSecretsTest() {
        // TODO: test imagePullSecrets
    }

    /**
     * Test the property 'nodeSelector'
     */
    @Test
    public void nodeSelectorTest() {
        // TODO: test nodeSelector
    }

    /**
     * Test the property 'onExit'
     */
    @Test
    public void onExitTest() {
        // TODO: test onExit
    }

    /**
     * Test the property 'parallelism'
     */
    @Test
    public void parallelismTest() {
        // TODO: test parallelism
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'serviceAccountName'
     */
    @Test
    public void serviceAccountNameTest() {
        // TODO: test serviceAccountName
    }

    /**
     * Test the property 'suspend'
     */
    @Test
    public void suspendTest() {
        // TODO: test suspend
    }

    /**
     * Test the property 'templates'
     */
    @Test
    public void templatesTest() {
        // TODO: test templates
    }

    /**
     * Test the property 'tolerations'
     */
    @Test
    public void tolerationsTest() {
        // TODO: test tolerations
    }

    /**
     * Test the property 'ttlSecondsAfterFinished'
     */
    @Test
    public void ttlSecondsAfterFinishedTest() {
        // TODO: test ttlSecondsAfterFinished
    }

    /**
     * Test the property 'volumeClaimTemplates'
     */
    @Test
    public void volumeClaimTemplatesTest() {
        // TODO: test volumeClaimTemplates
    }

    /**
     * Test the property 'volumes'
     */
    @Test
    public void volumesTest() {
        // TODO: test volumes
    }

}
