/*
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha1;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojWorkflowV1alpha1ValueFrom
 */
public class ValueFromTest {
    private final ValueFrom model = new ValueFrom();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1ValueFrom
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1ValueFrom() {
        // TODO: test IoArgoprojWorkflowV1alpha1ValueFrom
    }

    /**
     * Test the property 'jqFilter'
     */
    @Test
    public void jqFilterTest() {
        // TODO: test jqFilter
    }

    /**
     * Test the property 'jsonPath'
     */
    @Test
    public void jsonPathTest() {
        // TODO: test jsonPath
    }

    /**
     * Test the property 'parameter'
     */
    @Test
    public void parameterTest() {
        // TODO: test parameter
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

}
